# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn compile

    # Add the test step here
    - name: Testes de Unidade
      run: |
         mvn -Dtest=AdministratorTest test;
         mvn -Dtest=eWalletTest test;
         mvn -Dtest=PlayerTest test;
         mvn -Dtest=PlayGroundScheduleTest test;
         EXIT_CODE=$?
     #    mvn test -Dtest=PlaygroundOwnerTest test;
     #    mvn test -Dtest=PlaygroundTest test;
      if: always()
      
    - name: Teste UC01
      run:
        mvn test -Dtest=UC01Test test
      if: always()
      
    - name: Teste UC01Exception
      run:
        mvn -Dtest=UC01ExceptionTest test
      if: always()
      
    - name: Teste UC02
      run:
        mvn -Dtest=UC02Test test 
      if: always()
      
    - name: Teste UC02Exception
      run:
        mvn -Dtest=UC02ExceptionTest test 
      if: always()
      
    - name: Teste UC03
      run:
        mvn -Dtest=UC03Test test 
      if: always()

    - name: Teste UC03Exception
      run:
        mvn -Dtest=UC03ExceptionTest test 
      if: always()

    - name: Teste UC04
      run:
        mvn -Dtest=UC04Test test 
      if: always()

    - name: Teste UC04Exception
      run:
        mvn -Dtest=UC04ExceptionTest test 
      if: always()

    - name: Teste UC05
      run:
        mvn -Dtest=UC05Test test 
      if: always()

    - name: Teste UC05Exception01
      run:
        mvn -Dtest=UC05Exception01Test test 
      if: always()
      
    - name: Teste UC05Exception02
      run:
        mvn -Dtest=UC05Exception02Test test 
      if: always()
      
    - name: Teste UC06
      run:
        mvn -Dtest=UC06Test test 
      if: always()

    - name: Teste UC06Exception
      run:
        mvn -Dtest=UC06ExceptionTest test 
      if: always()

    - name: Teste UC07
      run:
        mvn -Dtest=UC07Test test 
      if: always()

    - name: Teste UC07Exception
      run:
        mvn -Dtest=UC07ExceptionTest test 
      if: always()

    - name: Teste UC08
      run:
        mvn -Dtest=UC08Test test 
      if: always()

    - name: Teste UC08Exception
      run:
        mvn -Dtest=UC08ExceptionTest test 
      if: always()

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
